#!/usr/bin/env bash
# Write a bash script that display time for 12 hours and 59 minutes
# DIsplay hours 0 to 12, display minutes from 1 to 59
min=1
hor=0
while((hor<=12));
do
	echo Hour: $hor
	while((min<60));
	do
		echo $min
		min=$((min+1))
	done
	min=1
	hor=$((hor+1))
done
